name: baseline-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # 请根据你实际python版本调整
  - pip
  - pip:
      - numpy==1.24.3
      - pandas==2.0.3
      - matplotlib==3.7.2
      - scikit-learn==1.3.0  # 你没列出，但你的代码依赖
      - torch==2.0.0         # 建议指定合适的torch版本
      - openpyxl==3.1.5
      - joblib==1.4.2
      - scipy                # 你的评估指标用到
      - tqdm                 # 可选，进度条
      - pyqt5==5.15.10       # matplotlib有时依赖
      - pillow==10.4.0
      - et-xmlfile==1.1.0
      - bottleneck==1.3.7
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - numexpr==2.8.4
      - fonttools==4.51.0
      - colorama==0.4.6
      - charset-normalizer==3.3.2
      - idna==3.7
      - importlib_resources==6.4.0
      - contourpy==1.0.5
      - cycler==0.11.0
      - kiwisolver==1.4.4
      - packaging==24.1
      - platformdirs==3.10.0
      - ply==3.11
      - pooch==1.7.0
      - pyparsing==3.0.9
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - mpmath==1.3.0
      - pytz
      - brotli==1.0.9