name: baseline-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - matplotlib
  - numpy
  - openpyxl
  - pip
  - pip:
    - torch==1.10.0
    - torchvision==0.11.1 